export const rideMapStyle = [
  { elementType: "geometry", stylers: [{ color: "#0D0D0D" }] },
  { elementType: "labels.icon", stylers: [{ visibility: "off" }] },
  { elementType: "labels.text.fill", stylers: [{ color: "#626262" }] },
  { elementType: "labels.text.stroke", stylers: [{ color: "#0D0D0D" }] },
  { featureType: "administrative", elementType: "geometry", stylers: [{ visibility: "off" }] },
  { featureType: "administrative.country", elementType: "labels", stylers: [{ visibility: "off" }] },
  { featureType: "administrative.locality", elementType: "labels", stylers: [{ visibility: "off" }] },
  { featureType: "landscape", elementType: "geometry", stylers: [{ color: "#0D0D0D" }] },
  { featureType: "landscape.man_made", elementType: "geometry", stylers: [{ color: "#0D0D0D" }] },
  { featureType: "poi", elementType: "geometry", stylers: [{ color: "#0D0D0D" }] },
  { featureType: "poi", elementType: "labels.text.fill", stylers: [{ color: "#6E6E6E" }] },
  { featureType: "road", elementType: "geometry", stylers: [{ color: "#303030" }] },
  { featureType: "road", elementType: "geometry.stroke", stylers: [{ color: "#303030" }] },
  { featureType: "road", elementType: "labels.text.fill", stylers: [{ color: "#525252" }] },
  { featureType: "road.highway", elementType: "geometry", stylers: [{ color: "#303030" }] },
  { featureType: "road.highway", elementType: "geometry.stroke", stylers: [{ color: "#303030" }] },
  { featureType: "road.highway", elementType: "labels", stylers: [{ visibility: "off" }] },
  { featureType: "road.arterial", elementType: "labels", stylers: [{ visibility: "off" }] },
  { featureType: "road.local", elementType: "labels", stylers: [{ visibility: "off" }] },
  { featureType: "transit", stylers: [{ visibility: "off" }] },
  { featureType: "water", elementType: "labels", stylers: [{ visibility: "off" }] },
  { featureType: "water", elementType: "geometry", stylers: [{ color: "#090909" }] },
];
